Carros = [
    {"id": 0, "marca": "Fiat", "nome": "Uno", "ano": 2001, "cor": "preto"},
    {"id": 1, "marca": "Volkswagen", "nome": "Gol", "ano": 2010, "cor": "prata"},
    {"id": 2, "marca": "Chevrolet", "nome": "Onix", "ano": 2015, "cor": "branco"},
    {"id": 3, "marca": "Ford", "nome": "Ka", "ano": 2018, "cor": "vermelho"},
    {"id": 4, "marca": "Hyundai", "nome": "HB20", "ano": 2013, "cor": "azul"},
    {"id": 5, "marca": "Renault", "nome": "Sandero", "ano": 2012, "cor": "cinza"},
    {"id": 6, "marca": "Toyota", "nome": "Corolla", "ano": 2017, "cor": "preto"},
    {"id": 7, "marca": "Honda", "nome": "Civic", "ano": 2016, "cor": "prata"},
    {"id": 8, "marca": "Nissan", "nome": "Versa", "ano": 2014, "cor": "branco"},
    {"id": 9, "marca": "Chevrolet", "nome": "Prisma", "ano": 2019, "cor": "vermelho"},
    {"id": 10, "marca": "Volkswagen", "nome": "Fox", "ano": 2008, "cor": "azul"},
    {"id": 11, "marca": "Fiat", "nome": "Palio", "ano": 2005, "cor": "cinza"},
    {"id": 12, "marca": "Ford", "nome": "Fiesta", "ano": 2011, "cor": "preto"},
    {"id": 13, "marca": "Toyota", "nome": "Etios", "ano": 2014, "cor": "branco"},
    {"id": 14, "marca": "Hyundai", "nome": "Creta", "ano": 2018, "cor": "prata"},
    {"id": 15, "marca": "Renault", "nome": "Kwid", "ano": 2019, "cor": "vermelho"},
    {"id": 16, "marca": "Honda", "nome": "Fit", "ano": 2017, "cor": "azul"},
    {"id": 17, "marca": "Volkswagen", "nome": "Saveiro", "ano": 2016, "cor": "cinza"},
    {"id": 18, "marca": "Chevrolet", "nome": "S10", "ano": 2015, "cor": "preto"},
    {"id": 19, "marca": "Fiat", "nome": "Toro", "ano": 2020, "cor": "branco"},
    {"id": 20, "marca": "Ford", "nome": "Ranger", "ano": 2019, "cor": "prata"},
    {"id": 21, "marca": "Toyota", "nome": "Hilux", "ano": 2018, "cor": "vermelho"},
    {"id": 22, "marca": "Hyundai", "nome": "Santa Fe", "ano": 2017, "cor": "azul"},
    {"id": 23, "marca": "Renault", "nome": "Duster", "ano": 2016, "cor": "cinza"},
    {"id": 24, "marca": "Honda", "nome": "HR-V", "ano": 2015, "cor": "preto"},
    {"id": 25, "marca": "Volkswagen", "nome": "T-Cross", "ano": 2019, "cor": "branco"},
    {"id": 26, "marca": "Chevrolet", "nome": "Tracker", "ano": 2020, "cor": "prata"},
    {"id": 27, "marca": "Fiat", "nome": "Mobi", "ano": 2017, "cor": "vermelho"},
    {"id": 28, "marca": "Ford", "nome": "EcoSport", "ano": 2018, "cor": "azul"},
    {"id": 29, "marca": "Toyota", "nome": "Rav4", "ano": 2019, "cor": "cinza"},
]



